---
title: "Blog"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## States of India and a demonstration of the 4 colour theorem



```{r cars}
library("leaflet")
library("rgdal")
library("ggmap")
library("raster")
library("htmlwidgets")

states <- readOGR("IndiaAdminUnits/States.shp")

colourIndex = c(1,1,1,2,2,3,2,3,1,3,2,2,3,2,3,2,1,1,3,1,1,1,3,3,3,2,1,4,2,3,3,1,1,4,1,4)
areas <- c(8249, 162968, 83743, 78438, 94163, 114, 135191, 491, 112, 3702, 196024, 44212, 55673, 222236, 79714, 191791, 38863, 32, 308350, 307713, 22327, 22429, 21081, 16579, 1484, 562, 50362, 342239, 7096, 130058, 112077, 10486, 243290, 53483, 88752, 155707)
states[["Area"]] <- areas
colors4 <- c("#3300FF", "#CCFF00", "#00B3FF", "#FF0000")

states[["ColourIndex"]] <- colourIndex
```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE}
map <- leaflet() %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states, 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              dashArray = "3",
              fillColor = colors4[states$ColourIndex],
              label = ~states$ST_NM,
              highlightOptions = highlightOptions(color = "white", weight = 2),
              popup = paste0("<strong>State name: </strong>",
                             states$ST_NM, 
                             "<br><strong>Area in square km: </strong>",
                             states$Area)) %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE)
map
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
