---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library("leaflet")
library("rgdal")
library("ggmap")
library("raster")
library("htmlwidgets")
#library("MapColoring")

districts <- readOGR("data/IndiaAdminUnits/Districts_2011.shp")
colors <- c(1,1,1,3,3,4,4,3,1,1,1,1,1,3,2,1,1,2,4,1,2,3,1,4,3,4,4,2,3,1,3,2,3,4,3,2,1,
            3,1,1,2,3,4,4,2,2,3,1,2,1,3,2,3,4,3,3,2,1,4,4,1,3,2,3,4,2,3,5,2,3,1,2,4,3,
            2,2,2,1,3,2,2,1,1,1,2,3,3,2,3,2,3,2,4,2,4,4,3,1,4,2,3,4,1,2,3,3,3,3,2,3,2,
            2,3,4,1,2,2,2,1,2,2,1,2,3,3,2,2,2,1,3,1,1,1,1,3,1,4,4,4,1,2,3,3,1,4,4,2,3,
            3,5,1,3,2,1,2,2,2,1,1,1,3,3,3,2,4,1,3,3,1,2,4,2,2,2,3,2,3,4,1,4,3,2,3,1,5,
            2,1,3,3,4,1,1,2,3,2,3,1,1,1,3,1,5,2,1,4,1,1,3,3,1,3,1,3,1,3,2,2,3,2,4,2,4,
            2,4,2,1,4,1,1,2,1,1,3,4,3,5,3,1,2,2,1,1,1,1,3,4,3,2,3,3,1,4,2,1,2,4,1,2,3,
            1,5,4,1,3,3,1,4,4,4,2,1,3,2,3,3,1,3,2,4,3,5,3,1,4,2,3,1,4,4,3,4,4,4,3,4,1,
            3,3,3,3,4,4,4,4,3,3,1,4,3,1,3,2,1,4,4,4,2,4,1,3,4,1,1,1,1,2,4,4,2,1,2,1,3,
            1,1,1,4,1,2,4,4,1,1,2,1,2,2,2,2,3,3,4,1,3,3,2,1,4,2,3,4,1,1,2,4,1,3,2,3,4,
            2,1,4,4,2,3,2,2,4,3,1,1,3,2,1,2,2,4,3,2,4,3,2,3,4,3,2,2,3,3,4,1,2,2,1,2,4,
            3,4,3,4,2,1,3,3,4,4,3,4,3,1,4,3,4,1,2,4,1,4,3,4,1,4,3,1,3,1,1,2,2,2,2,4,2,
            1,2,2,3,3,3,4,4,3,4,4,4,1,1,2,2,3,2,1,4,2,4,2,1,3,4,4,3,3,1,2,4,3,4,1,4,3,
            2,3,4,2,1,1,1,3,3,4,2,2,3,4,3,1,3,3,4,4,3,3,3,1,1,2,1,1,4,3,4,1,1,3,1,1,3,
            3,2,4,4,3,2,2,4,5,3,4,2,2,4,4,4,2,4,4,2,4,1,2,1,4,2,1,2,2,2,2,2,1,1,2,1,3,
            4,2,4,1,1,3,1,2,4,1,4,1,1,3,3,2,1,4,3,1,1,2,1,2,1,3,3,4,2,2,2,2,4,4,2,4,4,
            4,4,2,1,2,2,1,3,4,4,2,1,1,3,4,4,4,3,3,3,3,1,2,3,1,1,3,3,4,4,2,1,4,4,3,3,4,
            2,4,3,1,2,2,2,2,1,1,1,1)
# colors <- getColoring(districts)
# cand.colors <- rainbow(20)
# opt.colors <- getOptimalContrast(x=districts, col=cand.colors)
# par(mar=c(0,0,0,0))

colors4 <- c("#33FF00", "#001AFF", "#FF9900", "#FF004D", "#FF4D00")

districts[["ColourIndex"]] <- colors
```

## {.tabset}
### Districts of India

```{r, echo=FALSE, warning=F}
map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = districts, 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              dashArray = "3",
              fillColor = colors4[districts$ColourIndex],
              label = paste(~districts$DISTRICT),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              popup = paste0("<strong>District: </strong>",
                             districts$DISTRICT,
                             "<br><strong>State: </strong>",
                             districts$ST_NM)) %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE)
map
```

### Data

```{r}
library(DT)
datatable(districts@data, options = list(pageLength = 5))
```

### Info

Shape files from:
Demo of 4 colour theorem
Some anomalies