---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

<script>
  window.onload = function () {
    descendents = document.getElementsByClassName('leaflet-control');
    for(var i=0; i<descendents.length; i++) {
      if(descendents[i].className == 'info legend leaflet-control') {
        if (descendents[i].innerHTML.indexOf("Literacy Rate %") != -1) {
          descendents[i].style.display = 'block';
        } else {
          descendents[i].style.display = 'none';
        }
      }
    }
  }
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
options(java.parameters = "-Xmx4g" )
library(XLConnect)
library(sp)

wb <- loadWorkbook("data/Demographics/DistrictwiseTotalPopulation.xlsx")
populationData <- readWorksheet(wb, sheet = "TotalPopulation", header = TRUE)
populationData <- populationData[order(populationData$District),]
populationData[nrow(populationData)+2,] <- NA

districts <- readRDS("data/IndiaAdminUnits/Districts_2011_simplified.rds")
districts <- districts[order(as.numeric(districts$censuscode)),]

districts@data <- cbind(districts@data,  populationData[,])

```

```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library(leaflet)
library(leaflet.extras)
library(leaflet.minicharts)
library(ggmap)
library(raster)
library(htmltools)
library(htmlwidgets)
library(legendreverse)

round_percent <- function(x) { 
  if(!any(is.na(x))) {
    x <- x/sum(x)*100  # Standardize result
    res <- floor(x)    # Find integer bits
    rsum <- sum(res)   # Find out how much we are missing
    if(rsum<100) { 
        # Distribute points based on remainders and a random tie breaker
        o <- order(x%%1, sample(length(x)), decreasing=TRUE) 
        res[o[1:(100-rsum)]] <- res[o[1:(100-rsum)]]+1
    } 
    res 
  }
}

hoverlabelsLit <- lapply(seq(nrow(districts@data)), function(i) {
  if (is.na(districts@data$Literacy.Rate..[i])) {
    return(paste0('<p>', sprintf(
        "<div style='font-size:12px;width:200px;float:left'>
        <hr><span style='font-size:12px;font-weight:bold'>%s</span><br/>",         districts@data$DISTRICT[i])))
  }
  paste0( '<p>', sprintf(
        "<div style='font-size:12px;width:200px;float:left'>
        <hr><span style='font-size:12px;font-weight:bold'>%s</span><br/>
        <div style='width:95%%'>
        <span style='float:left'>Population:</span>
        <span style='float:right'> %s </span><br/>
        <span style='float:left'>Literacy Rate (%%):</span>
        <span style='float:right'> %s </span><br/>
        <span style='float:left'>Non-Literates:</span>
        <span style='float:right'>&asymp;%s </span><br/>
        </div>
        </div>",
        districts@data$DISTRICT[i],
        districts@data$Total.Population[i],
        districts@data$Literacy.Rate..[i],
        format((100.0 - districts@data$Literacy.Rate..[i])*districts@data$Total.Population[i], big.mark=",")
      ), '</p>' ) 
})

```
## {.tabset}
### India, Districtwise Literacy Info (2011 Census)^[1]^

<div class = "col-md-8">
<div class = "row">
```{r, echo=FALSE, warning=F}
YlOrBr <- c('#ffffcc', '#ffeda0', '#fed976', '#feb24c', '#fd8d3c', '#fc4e2a', '#e31a1c', '#bd0026', '#800026')

mapspaletteLit  <- colorNumeric(
  palette = "Blues",
  domain = districts@data$Literacy.Rate..)

map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>%
  leafem::addMouseCoordinates() %>% 
  
  addPolygons(data = districts,
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor =  ~mapspaletteLit(districts@data$Literacy.Rate..),
              label = lapply(hoverlabelsLit, htmltools::HTML),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Literacy Rate %") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  leafem::addMouseCoordinates() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  addResetMapButton() %>%
  addSearchOSM(options = search) %>%
  addFullscreenControl() %>% 

  legendreverse("bottomleft", pal = mapspaletteLit, values = districts@data$Literacy.Rate.., title = "Literacy Rate %", opacity = 1, decreasing = T) %>%
  
htmlwidgets::onRender("
    function(el, x) {
      var myMap = this;
      myMap.on('baselayerchange',
        function (e) {
          document.getElementById('countryInfo').innerHTML = lookupCountryInfo(e.name);
          descendents = document.getElementsByClassName('leaflet-control')
          for(var i=0; i<descendents.length; i++) {
            if(descendents[i].className == 'info legend leaflet-control') {
              if (descendents[i].innerHTML.indexOf(e.name) != -1) {
                descendents[i].style.display = 'block';
              } else {
                descendents[i].style.display = 'none';
              }
            }
          }
        })

      myMap.on('tooltipopen',
        function (e) {
          document.getElementById('districtInfo').innerHTML = e.tooltip._content;
          $('.leaflet-tooltip').css('display','none');
        })

      myMap.on('tooltipclose',
        function (e) {
          document.getElementById('districtInfo').innerHTML = '';
        })
    }") %>% 
  
  addLayersControl(
    baseGroups = c("Literacy Rate %"),
    options = layersControlOptions(collapsed = FALSE)
  )

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
  map <- map %>% prependContent(tags$style(type = "text/css", css_fix))  

map

```
<font size='1'>*2011 data and boundaries<br/>
Sources:<br/>
[1] http://www.censusindia.gov.in/2011census/population_enumeration.html <br/>
[2] https://en.wikipedia.org/wiki/List_of_districts_in_India
</font>
</div>
</div>
<div class = "col-md-3">
<div class = "row"  style = "margin-left: 10px">
<h2><b>India</b></h2>
<div id = "countryInfo">
<p><div style='width:95%%'><div style='font-size:12px;width:200px;float:left'><span style='float:left'>Literacy Rate:</span><span style='float:right'> 74.04 %</span><br/><span style='float:left'>Population:</span><span style='float:right'> 1,210,854,977</span><br/><span style='float:left'>Non-literate:</span><span style='float:right'> &asymp;314,337,952</span></div></div></p>
</div>
<div id = "districtInfo">
</div>
</div>
</div>

### Data

```{r}
# library(DT)
# populationData <- populationData[order(populationData$Rank),]
# datatable(populationData, rownames = FALSE)
```

Source: http://www.censusindia.gov.in/2011census/population_enumeration.html

### Info
