---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library("leaflet")
library("leaflet.minicharts")
library("rgdal")
library("rvest")
library("tidyverse")
library("ggmap")
library("raster")
library("sp")
library("htmlwidgets")

states <- readOGR("data/IndiaAdminUnits/States.shp")

url <- 'https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_sex_ratio'
ratio <- url %>%
  read_html() %>%
  html_nodes(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>%
  html_table()
ratio <- ratio[[1]][-1,]
ratio <- ratio[-c(1,4,6:10)]
row.names(ratio) <- NULL
names(ratio)[1] <- "State Name"
puducherry2011 <- ratio[2,2]
ratio[2,2] = "NA"
damandiu2011 <- ratio[36,2]
ratio[36,2] = "NA"
dadranagarhaveli2011 <- ratio[35,2]
ratio[35,2] = "NA"
chandigarh2011 <- ratio[34,2]
ratio[34,2] = "NA"
puducherry2001 <- ratio[2,3]
ratio[2,3] = "NA"
damandiu2001 <- ratio[36,3]
ratio[36,3] = "NA"
dadranagarhaveli2001 <- ratio[35,3]
ratio[35,3] = "NA"
chandigarh2001 <- ratio[34,3]
ratio[34,3] = "NA"
ratio$`2011 Census` <- as.integer(ratio$`2011 Census`)
ratio$`2001 Census` <- as.integer(ratio$`2001 Census`)
ratio$`State Name`[33] = "NCT of Delhi"
ratio <- ratio[order(ratio[1]),]
states <- states[order(states$ST_NM),]
states[["Ratio 2011"]] <- ratio[2]
states[["Ratio 2001"]] <- ratio[3]

pal <- colorNumeric(
  palette = "YlOrRd",
  reverse = TRUE,
  domain = c(ratio$`2011 Census`,ratio$`2001 Census`)
)

```

## {.tabset}
### States of India

```{r, echo=FALSE, warning=F}
#addLegend_decreasing lifted from: https://github.com/rstudio/leaflet/issues/256#issuecomment-440290201

addLegend_decreasing <- function (map, position = c("topright", "bottomright", "bottomleft", 
			    "topleft"), pal, values, na.label = "NA", bins = 7, colors, 
		  opacity = 0.5, labels = NULL, labFormat = labelFormat(), 
		  title = NULL, className = "info legend", layerId = NULL, 
		  group = NULL, data = getMapData(map), decreasing = FALSE) {
	position <- match.arg(position)
	type <- "unknown"
	na.color <- NULL
	extra <- NULL
	if (!missing(pal)) {
		if (!missing(colors)) 
			stop("You must provide either 'pal' or 'colors' (not both)")
		if (missing(title) && inherits(values, "formula")) 
			title <- deparse(values[[2]])
		values <- evalFormula(values, data)
		type <- attr(pal, "colorType", exact = TRUE)
		args <- attr(pal, "colorArgs", exact = TRUE)
		na.color <- args$na.color
		if (!is.null(na.color) && col2rgb(na.color, alpha = TRUE)[[4]] == 
		    0) {
			na.color <- NULL
		}
		if (type != "numeric" && !missing(bins)) 
			warning("'bins' is ignored because the palette type is not numeric")
		if (type == "numeric") {
			cuts <- if (length(bins) == 1) 
				pretty(values, bins)
			else bins	
			
			if (length(bins) > 2) 
				if (!all(abs(diff(bins, differences = 2)) <= 
				         sqrt(.Machine$double.eps))) 
					stop("The vector of breaks 'bins' must be equally spaced")
			n <- length(cuts)
			r <- range(values, na.rm = TRUE)
			cuts <- cuts[cuts >= r[1] & cuts <= r[2]]
			n <- length(cuts)
			p <- (cuts - r[1])/(r[2] - r[1])
			extra <- list(p_1 = p[1], p_n = p[n])
			p <- c("", paste0(100 * p, "%"), "")
			if (decreasing == TRUE){
				colors <- pal(rev(c(r[1], cuts, r[2])))
				labels <- rev(labFormat(type = "numeric", cuts))
			}else{
				colors <- pal(c(r[1], cuts, r[2]))
				labels <- rev(labFormat(type = "numeric", cuts))
			}
			colors <- paste(colors, p, sep = " ", collapse = ", ")
			
		}
		else if (type == "bin") {
			cuts <- args$bins
			n <- length(cuts)
			mids <- (cuts[-1] + cuts[-n])/2
			if (decreasing == TRUE){
				colors <- pal(rev(mids))
				labels <- rev(labFormat(type = "bin", cuts))
			}else{
				colors <- pal(mids)
				labels <- labFormat(type = "bin", cuts)
			}
			
		}
		else if (type == "quantile") {
			p <- args$probs
			n <- length(p)
			cuts <- quantile(values, probs = p, na.rm = TRUE)
			mids <- quantile(values, probs = (p[-1] + p[-n])/2, 
				 na.rm = TRUE)
			if (decreasing == TRUE){
				colors <- pal(rev(mids))
				labels <- rev(labFormat(type = "quantile", cuts, p))
			}else{
				colors <- pal(mids)
				labels <- labFormat(type = "quantile", cuts, p)
			}
		}
		else if (type == "factor") {
			v <- sort(unique(na.omit(values)))
			colors <- pal(v)
			labels <- labFormat(type = "factor", v)
			if (decreasing == TRUE){
				colors <- pal(rev(v))
				labels <- rev(labFormat(type = "factor", v))
			}else{
				colors <- pal(v)
				labels <- labFormat(type = "factor", v)
			}
		}
		else stop("Palette function not supported")
		if (!any(is.na(values))) 
			na.color <- NULL
	}
	else {
		if (length(colors) != length(labels)) 
			stop("'colors' and 'labels' must be of the same length")
	}
	legend <- list(colors = I(unname(colors)), labels = I(unname(labels)), 
	               na_color = na.color, na_label = na.label, opacity = opacity, 
	               position = position, type = type, title = title, extra = extra, 
	               layerId = layerId, className = className, group = group)
	invokeMethod(map, data, "addLegend", legend)
}

adult2011 <- c("ST_NM" ,"Ratio 2011")
adult2001 <- c("ST_NM", "Ratio 2001")

map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states[adult2011], 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor = ~pal(ratio$`2011 Census`),
              label = paste(states$ST_NM,": ",ratio$`2011 Census`),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "2011") %>%
  
  addPolygons(data = states[adult2001], 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor = ~pal(ratio$`2001 Census`),
              label = paste0(states$ST_NM,": ",ratio$`2001 Census`),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "2001") %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  addLegend_decreasing("bottomleft", pal = pal, values = na.omit(ratio$`2011 Census`),
    title = "Females per 1k males",
    opacity = 1,
    decreasing = TRUE,
    group = "2011"
  ) %>% 
  addLayersControl(
    baseGroups = c("2011", "2001"),
    options = layersControlOptions(collapsed = FALSE)
  )

map
```

### Data

```{r}
library(DT)
ratio[6,2] <- as.integer(chandigarh2011)
ratio[8,2] <- as.integer(dadranagarhaveli2011)
ratio[9,2] <- as.integer(damandiu2011)
ratio[27,2] <- as.integer(puducherry2011)
ratio[6,3] <- as.integer(chandigarh2001)
ratio[8,3] <- as.integer(dadranagarhaveli2001)
ratio[9,3] <- as.integer(damandiu2001)
ratio[27,3] <- as.integer(puducherry2001)
datatable(ratio[order(-ratio[2]),], options = list(pageLength = 36))
```

### Info

Shape files from:
Demo of 4 colour theorem