---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library("leaflet")
library("rgdal")
library("ggmap")
library("raster")
library("sp")
library("htmlwidgets")

railnet <- geojsonio::geojson_read("data/Transportation/trains.json", what = "sp")
```

## {.tabset}
### Railway Network of India

```{r, echo=FALSE, warning=F}
map <- leaflet(width = "100%") %>%
  setView(82, 25, zoom = 4) %>%
  addProviderTiles(providers$Stamen.Terrain) %>% 
  addTiles(urlTemplate = "http://{s}.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png",
           attribution = '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>, Style: <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA 2.0</a> <a href="http://www.openrailwaymap.org/">OpenRailwayMap</a> and OpenStreetMap') %>%
  addPolylines(data = railnet, 
              weight = 3,
              opacity = 0.,
              label = railnet$name,
              group = "trains") %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE)
map
```

### Data

```{r}
library(DT)
datatable(railnet@data, options = list(pageLength = 100))
```

### Info

