---
title: "Parliament Constituencies of India"
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library("leaflet")
library("rgdal")
library("ggmap")
library("raster")
library("htmlwidgets")

parliamentconstituencies <- readOGR("IndiaAdminUnits/ParliamentaryConstituencies_2014.shp")
colors <- c(1,3,1,1,4,2,3,2,2,3,3,3,2,4,4,1,3,3,1,4,2,5,3,1,2,3,4,1,2,3,2,1,4,2,3,4,3,
4,2,4,4,4,1,2,4,1,4,3,3,2,2,1,3,2,2,1,3,3,1,4,3,3,1,4,2,2,1,2,1,1,4,2,3,3,
3,4,4,3,2,2,3,1,4,3,1,4,1,1,3,1,3,2,3,3,1,4,4,2,1,2,4,1,3,1,2,1,3,4,1,4,4,
1,1,3,2,1,4,3,5,1,2,1,1,3,2,3,4,1,2,1,3,1,2,4,2,1,1,3,1,4,4,3,2,3,2,4,2,1,
3,4,2,1,4,1,2,4,3,2,1,3,2,1,3,2,1,3,2,1,2,2,4,5,3,2,4,3,3,1,2,2,1,1,3,1,4,
2,1,2,3,1,2,2,4,3,1,2,1,2,1,4,4,1,1,3,1,3,2,1,4,3,2,3,4,1,1,1,4,3,2,2,1,1,
3,1,3,2,1,1,3,3,1,2,1,3,3,4,5,3,2,2,3,1,1,3,2,1,2,1,3,4,3,4,1,4,3,4,2,2,4,
2,1,1,2,3,3,1,1,4,2,4,2,4,2,1,3,4,4,1,1,3,2,3,4,2,4,2,2,2,4,4,1,3,2,1,4,3,
2,2,1,3,2,3,1,2,1,3,4,3,4,1,1,3,1,3,4,4,1,2,4,1,2,3,3,4,1,1,2,1,2,4,3,2,3,
4,1,2,4,1,2,2,4,1,3,3,3,2,4,1,2,4,3,4,3,4,1,3,2,1,2,4,1,3,3,1,4,2,3,1,2,4,
3,1,3,1,1,2,3,2,3,4,1,3,2,2,2,4,1,3,4,1,2,4,3,2,1,4,3,1,3,4,4,4,1,3,2,3,2,
2,3,1,3,2,1,1,2,2,3,1,4,1,2,3,5,4,1,4,1,2,2,4,3,4,2,3,4,4,1,2,3,2,4,1,3,1,
2,4,2,3,4,2,2,1,1,4,2,2,1,3,4,2,4,1,1,3,4,1,3,2,1,3,1,2,2,1,3,2,4,2,3,3,2,
2,3,1,1,3,4,1,2,4,3,1,4,4,2,5,1,1,1,2,3,1,3,4,1,1,2,3,1,2,3,3,1,4,1,4,4,1,
2,4,2,2,2,1,4,3,2,2,4,3,1,2,1,1,1,2,3,3,1,2,3,2,2,1)

colors4 <- c("#33FF00", "#001AFF", "#FF9900", "#FF004D", "#FF4D00")

parliamentconstituencies[["ColourIndex"]] <- colors
```

## {.tabset .tabset-fade}
### Map

```{r, echo=FALSE, warning=F}
map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = parliamentconstituencies, 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              dashArray = "3",
              fillColor = colors4[parliamentconstituencies$ColourIndex],
              label = ~parliamentconstituencies$PC_NAME,
              highlightOptions = highlightOptions(color = "white", weight = 2),
              popup = paste0("<strong>District: </strong>",
                             parliamentconstituencies$PC_NAME,
                             "<br><strong>State: </strong>",
                             parliamentconstituencies$ST_NAME)) %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE)
map
```

### Data

```{r}
print(parliamentconstituencies$PC_NAME)
```

