---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library(leaflet)
library(leaflet.minicharts)
library(rgdal)
library(RCurl)
library(XML)
library(tidyverse)
library(ggmap)
library(raster)
library(sp)
library(htmltools)
library(htmlwidgets)
library(legendreverse)
library(data.table)

round_percent <- function(x) { 
  if(!is.na(x)) {
    x <- x/sum(x)*100  # Standardize result
    res <- floor(x)    # Find integer bits
    rsum <- sum(res)   # Find out how much we are missing
    if(rsum<100) { 
        # Distribute points based on remainders and a random tie breaker
        o <- order(x%%1, sample(length(x)), decreasing=TRUE) 
        res[o[1:(100-rsum)]] <- res[o[1:(100-rsum)]]+1
    } 
    res 
  }
}

states <- readOGR("data/IndiaAdminUnits/States_2011.shp", stringsAsFactors = FALSE)
states <- states[order(states$State.Name),]
centroids <- getSpPPolygonsLabptSlots(states)
states[['Centroids']] <- centroids

url <- 'https://en.wikipedia.org/wiki/2011_Census_of_India'
url_parsed <- htmlParse(getURL(url), asText = TRUE)
tableNodes <- getNodeSet(url_parsed, '//*[@id="mw-content-text"]/div/table[6]')
populationData <- readHTMLTable(tableNodes[[1]], header=TRUE, colClasses = c("integer", rep("character",3), "FormattedInteger", "double", rep("FormattedInteger", 3), "double", rep("FormattedInteger",4), "Percent"))

setnames(populationData, old = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15), new = c("Rank", "State/UT Name", "Capitals", "Type", "Population", "% of Total Population", "Males", "Females", "Gender Ratio", "Literacy Rate (%)", "Rural Population", "Urban Population", "Area (sqkm)", "Density (per sqkm)", "Decadal Growth%(2001-2011)"))

populationData <- populationData[-36,]

populationData["Urban Rural Ratio"] <- round(populationData$`Urban Population`/populationData$`Rural Population`,2) 
populationData["Urban %"] <- round(100*populationData$`Urban Population`/populationData$Population,2)
populationData["Rural %"] <- round(100*populationData$`Rural Population`/populationData$Population,2)


populationData <- populationData[order(populationData$`State/UT Name`),]

#Add NAs for parts of Kashmir outside LOC
populationData[nrow(populationData)+1,] <- NA
populationData[36, "Area (sqkm)"] <- 123512
states@data[36, "State.Name"] <- "Outside LOC"

states@data <- cbind(states@data,  populationData[,3:18])

plotSubset <- subset(states, states$`Area (sqkm)` > 1500)

```

## {.tabset}
### Population Density*

```{r, echo=FALSE, warning=F}
#Hover content
hoverlabels <- lapply(seq(nrow(states@data)), function(i) {
  paste0( '<p>', sprintf(
        "<div style='width:95%%'>
        <div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><hr>
        <span style='float:left'>Population : %s (%s%%)</span><br/>
        <span style='float:left'>Area (sqkm): %s (%s%%)</span><br/>
        <span style='float:left'>Population Density: %s per sqkm</span>
        </div>
        </div>",
        states@data[i, "State.Name"],
        format(states@data[i, "Population"], big.mark=","),
        states@data[i, "% of Total Population"],
        format(states@data[i, "Area (sqkm)"], big.mark=","), 
        format(round(100.0*states@data[i, "Area (sqkm)"]/3287240,2)),
        states@data[i, "Density (per sqkm)"]
      ), '</p>' ) 
})

mapspalette <- colorNumeric(
  palette = "YlOrRd",
  domain = plotSubset$`Density (per sqkm)`
)

map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states,
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor = ~mapspalette(states$`Density (per sqkm)`),
              label = lapply(hoverlabels, htmltools::HTML),
              labelOptions = labelOptions(
                offset=c(-100,-140),
                textOnly = T,
                style=list(
                  'background'='rgba(255,255,255,0.95)',
                  'border-color' = 'rgba(0,0,0,1)',
                  'border-radius' = '10px',
                  'border-style' = 'solid',
                  'border-width' = '2px')),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Population Density") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  addLegend("bottomleft", pal = mapspalette, values = plotSubset$`Density (per sqkm)`, title = "Population Density", opacity = 1, group = "Population Density", layerId = "Population Density" )

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
map <- map %>% prependContent(tags$style(type = "text/css", css_fix))  

map
  
```
*2011 Census and State/UT boundaries

### Population Growth% 2001-2011*

```{r, echo=FALSE, warning=F}
#Hover content
hoverlabels <- lapply(seq(nrow(states@data)), function(i) {
  paste0( '<p>', sprintf(
        "<div style='width:95%%'>
        <div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><hr>
        <span style='float:left'>Population Growth: %s %%</span><br/>
        <span style='float:left'>Population: %s</span><br/>
        </div>
        </div>",
        states@data[i, "State.Name"],
        states@data[i, "Decadal Growth%(2001-2011)"],
        format(states@data[i, "Population"], big.mark=",")
      ), '</p>' ) 
})

mapspalette <- colorNumeric(
  palette = "YlOrRd",
  domain = plotSubset$`Decadal Growth%(2001-2011)`
)

map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states,
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor = ~mapspalette(states$`Decadal Growth%(2001-2011)`),
              label = lapply(hoverlabels, htmltools::HTML),
              labelOptions = labelOptions(
                offset=c(-100,-140),
                textOnly = T,
                style=list(
                  'background'='rgba(255,255,255,0.95)',
                  'border-color' = 'rgba(0,0,0,1)',
                  'border-radius' = '10px',
                  'border-style' = 'solid',
                  'border-width' = '2px')),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Population Growth %") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  addLegend("bottomleft", pal = mapspalette, values = plotSubset$`Decadal Growth%(2001-2011)`, title = "Population Growth %", opacity = 1, group = "Population Growth %", layerId = "Population Growth %" )

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
map <- map %>% prependContent(tags$style(type = "text/css", css_fix))  

map
  
```
*2011 Census and State/UT boundaries

### Literacy Rate(%)*

```{r, echo=FALSE, warning=F}
#Hover content
hoverlabels <- lapply(seq(nrow(states@data)), function(i) {
  paste0( '<p>', sprintf(
        "<div style='width:95%%'>
        <div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><hr>
        <span style='float:left'>Literacy Rate: %s %%</span><br/>
        <span style='float:left'>Population: %s</span><br/>
        <span style='float:left'>Non-literate: %s</span><br/>
        </div>
        </div>",
        states@data[i, "State.Name"],
        states@data[i, "Literacy Rate (%)"],
        format(states@data[i, "Population"], big.mark=","),
        format(round((100-states@data[i, "Literacy Rate (%)"])*states@data[i, "Population"]/100.0,0), big.mark=",")
      ), '</p>' ) 
})

mapspalette <- colorNumeric(
  palette = "Blues",
  domain = plotSubset$`Literacy Rate (%)`
)

map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states,
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.8,
              dashArray = "3",
              fillColor = ~mapspalette(states$`Literacy Rate (%)`),
              label = lapply(hoverlabels, htmltools::HTML),
              labelOptions = labelOptions(
                offset=c(-100,-140),
                textOnly = T,
                style=list(
                  'background'='rgba(255,255,255,0.95)',
                  'border-color' = 'rgba(0,0,0,1)',
                  'border-radius' = '10px',
                  'border-style' = 'solid',
                  'border-width' = '2px')),
              highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Literacy Rate %") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  legendreverse("bottomleft", pal = mapspalette, values = plotSubset$`Literacy Rate (%)`, title = "Literacy Rate %", opacity = 1, group = "Literacy Rate %", layerId = "Literacy Rate %" , decreasing = T)

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
map <- map %>% prependContent(tags$style(type = "text/css", css_fix))
  
map
  
```
*2011 Census and State/UT boundaries

### Gender Ratio*

```{r, echo=FALSE, warning=F}
#Hover content
hoverlabels <- lapply(seq(nrow(states@data)), function(i) {
  if (is.na(states@data[i, "Males"]) || is.na(states@data[i, "Females"])) {
    return(states@data[i, "State.Name"])
  }
  nums <- round_percent(c(100*states@data[i, "Males"]/states@data[i, "Population"],100*states@data[i, "Females"]/states@data[i, "Population"]))
  paste0( '<p>', sprintf(
        "<div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><hr>
        Gender Ratio: %s<br/>
        <div style='width:95%%'>
        <span style='float:left'>Males</span>
        <span style='float:right'>Females</span>
        <br/>
        <span style='color:#2aa1ec;float:left'>%s%%</span>
        <span style='color:#fe6a59;float:right'>%s%%</span><br clear='all'/>
        <span style='background:#2aa1ec;width:%s%%;float:left'>&nbsp;</span>
        <span style='background:#fe6a59;width:%s%%;float:right'>&nbsp;</span><hr>
        <span style='float:left'>Males: </span>
        <span style='float:right'>%s</span><br/>
        <span style='float:left'>Females: </span>
        <span style='float:right'>%s</span><br/>
        <span style='float:left'>Difference: </span>
        <span style='float:right'>%s</span>
        </div>
        </div>",
        states@data[i, "State.Name"],
        states@data[i, "Gender Ratio"],
        nums[1], nums[2],
        nums[1], nums[2],
        format(states@data[i, "Males"], big.mark=","), format(states@data[i, "Females"], big.mark=","), format(states@data[i, "Males"] - states@data[i, "Females"], big.mark=",")
      ), '</p>' ) 
})

mapspalette <- colorNumeric(
  palette = "YlOrRd",
  reverse = TRUE,
  domain = plotSubset$`Gender Ratio`
)

map <- leaflet(width = "100%") %>%
  addProviderTiles("Esri") %>% 
  addPolygons(
    data = states,
    color = "#000000", 
    weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.8,
    dashArray = "3",
    fillColor = ~mapspalette(as.numeric(states$`Gender Ratio`)),
    label = lapply(hoverlabels, htmltools::HTML),
    labelOptions = labelOptions(
      offset=c(-100,-140),
      textOnly = T,
      style=list(
        'background'='rgba(255,255,255,0.95)',
        'border-color' = 'rgba(0,0,0,1)',
        'border-radius' = '10px',
        'border-style' = 'solid',
        'border-width' = '2px')),
    highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Gender Ratio") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  legendreverse("bottomleft", pal = mapspalette, values = plotSubset$`Gender Ratio`, opacity = 1, decreasing = TRUE, title = "Gender Ratio", group = "Gender Ratio", layerId = "Gender Ratio" )

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
map <- map %>% prependContent(tags$style(type = "text/css", css_fix))
  
map
  
```
*2011 Census and State/UT boundaries

### Urban:Rural Ratio*

```{r, echo=FALSE, warning=F}
# Hover content
hoverlabels <- lapply(seq(nrow(states@data)), function(i) {
  if (is.na(states@data[i, "Urban Population"]) || is.na(states@data[i, "Rural Population"])) {
    return(states@data[i, "State.Name"])
  }
  nums <- round_percent(c(as.numeric(states@data[i, "Urban %"]),as.numeric(states@data[i, "Rural %"])))
  paste0( '<p>', sprintf(
        "<div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><hr>
        Urban:Rural Ratio: %s<br/>
        <div style='width:95%%'>
        <span style='float:left'>Urban</span>
        <span style='float:right'>Rural</span>
        <br/>
        <span style='color:#2aa1ec;float:left'>%s%%</span>
        <span style='color:#fe6a59;float:right'>%s%%</span><br clear='all'/>
        <span style='background:#2aa1ec;width:%s%%;float:left'>&nbsp;</span>
        <span style='background:#fe6a59;width:%s%%;float:right'>&nbsp;</span><hr>
        <span style='float:left'>Urban Population: </span>
        <span style='float:right'>%s</span><br/>
        <span style='float:left'>Rural Population: </span>
        <span style='float:right'>%s</span><br/>
        <span style='float:left'>Total Population: </span>
        <span style='float:right'>%s</span>
        </div>
        </div>",
        states@data[i, "State.Name"],
        states@data[i, "Urban Rural Ratio"],
        nums[1],nums[2],
        nums[1],nums[2],
        format(states@data[i, "Urban Population"], big.mark=","), format(states@data[i, "Rural Population"], big.mark=","), format(states@data[i, "Population"], big.mark=",")
      ), '</p>' ) 
})

mapspalette <- colorNumeric(
  palette = "YlOrRd",
  reverse = T,
  domain = as.numeric(plotSubset@data$`Urban Rural Ratio`)
)

map <- leaflet(width = "100%") %>%
  addProviderTiles("Esri") %>% 
  addPolygons(
    data = states,
    color = "#000000", 
    weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.8,
    dashArray = "3",
    fillColor = ~mapspalette(as.numeric(states$`Urban Rural Ratio`)),
    label = lapply(hoverlabels, htmltools::HTML),
    labelOptions = labelOptions(
      offset=c(-100,-140),
      textOnly = T,
      style=list(
        'background'='rgba(255,255,255,0.95)',
        'border-color' = 'rgba(0,0,0,1)',
        'border-radius' = '10px',
        'border-style' = 'solid',
        'border-width' = '2px')),
    highlightOptions = highlightOptions(color = "white", weight = 2),
              group = "Urban:Rural") %>%
  
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  addSimpleGraticule(showOriginLabel = TRUE) %>%
  legendreverse("bottomleft", pal = mapspalette, values = as.numeric(plotSubset$`Urban Rural Ratio`), decreasing = T, opacity = 1, title = "Urban:Rural", group = "Urban:Rural", layerId = "Urban:Rural" )

css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
map <- map %>% prependContent(tags$style(type = "text/css", css_fix))
  
map

```
*2011 Census and State/UT boundaries

### Data

```{r}
library(DT)
populationData <- populationData[order(populationData$Rank),]
populationData <- populationData[-36,]
col2cnvrt <- c(1, 5:18)
col2cnvrt2 <- c(0, 4:17) #because !#$@# columnDefs indexes from 0
populationData[,col2cnvrt] <- lapply(populationData[,col2cnvrt],function(x){format(round(as.numeric(x), 2), big.mark=",")})
datatable(populationData, rownames = FALSE, options = list(pageLength = 35, columnDefs = list(list(className = 'dt-right', targets = col2cnvrt2))))
```

Source: https://en.wikipedia.org/wiki/Demographics_of_India#Census_of_India:_sample_registration_system

### Info
