---
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
        padding: 0;
        margin: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=F, warning=F, results = 'hide'}
library(leaflet)
library(rgdal)
library(ggmap)
library(raster)
library(sp)
library(htmlwidgets)
library(htmltools) 

states <- readRDS("data/IndiaAdminUnits/States_Aug2019_simplified_1.rds")
states <- states[order(as.numeric(states$ID_1)),]

colourIndex = c(2,4,3,4,1,1,1,1,1,3,3,2,4,3,4,4,1,4,1,1,3,4,2,3,3,1,3,1,2,1,3,2,2,1,2,1,2,5)

#Source: https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
areas <- c("8,249", "162,970", "83,743", "78,438", "94,165", "114", "135,191", "491", "112", "1,483", "3,702", "196,024", "44,212", "55,673", "42,241", "79,714", "191,791", "38,863", "59,146", "32", "308,350", "307,713", "22,327", "22,429", "21,081", "16,579", "155,707", "492", "50,362", "342,238", "7,096", "130,058", "112,077", "10,486", "243,290", "53,483", "88,752", NA)
states[["Area (sqkm)"]] <- areas
colors4 <- c("#3300FF", "#CCFF00", "#00B3FF", "#FF0000", "#999999")

```

## {.tabset}
### States and Union Territories of India^[1]^

<div class = "col-md-8">
<div class = "row">
```{r, echo=FALSE, warning=F}

labelsInfo <- lapply(seq(nrow(states@data)), function(i) {
  if(i<38) {
    paste0( '<p>', sprintf(
       "<div style='width:95%%'>
        <div style='font-size:12px;width:200px;float:left'>
        <span style='font-size:12px;font-weight:bold'>%s</span><br/>
        <span style='float:left'>Area : %s (sqkm)</span><br/>
        <span style='float:left'>Type : %s </span><br/>
        </div>
        </div>",
        states@data[i, "State...UT"],
        states@data[i, "Area (sqkm)"],
        states@data[i, "Type"])
      , '</p>' )
  }
})


map <- leaflet(width = "100%") %>% 
  addProviderTiles("Esri") %>% 
  addPolygons(data = states, 
              color = "#000000", 
              weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              dashArray = "3",
              fillColor = colors4[colourIndex],
              label = lapply(labelsInfo, htmltools::HTML),
              highlightOptions = highlightOptions(color = "white", weight = 2)) %>%
  addMiniMap(tiles = providers$Esri, toggleDisplay = TRUE) %>% 
  addScaleBar() %>%
  leafem::addMouseCoordinates() %>%
  addSimpleGraticule(showOriginLabel = TRUE)%>%
  htmlwidgets::onRender("
    function(el, x) {
      var myMap = this;
      myMap.on('tooltipopen',
        function (e) {
          $('.leaflet-tooltip').css('display','none');
          document.getElementById('stateInfo').innerHTML = e.tooltip._content;
        })
      myMap.on('tooltipclose',
        function (e) {
          document.getElementById('stateInfo').innerHTML = '';
        })
    }")
map
```
<font size='1'>*As of August 2019<br/>
Sources:<br/>
[1] https://en.wikipedia.org/wiki/Geography_of_India <br/>
[2] https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
</font>
</div>
</div>
<div class = "col-md-3">
<div class = "row"  style = "margin-left: 10px">
<div id = "countryInfo">
<h2><b>India</b></h2>
<h5>Total area: 3.287 million sqkm<sup>[2]</sup> </h5>
</div>
<div id = "stateInfo">
</div>
</div>
</div>

### Data^[1]^
```{r}
#Here Column indices start from 0 !#$$!@#
library(DT)
datatable(states@data, rownames = FALSE, options = list(pageLength = 38, columnDefs = list(list(className = 'dt-right', targets = 3))))
```
<font size='1'>
Sources:<br/>
[1] https://en.wikipedia.org/wiki/Geography_of_India <br>
[2] https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
</font>

### Info
```{r}
sessionInfo()
```

